sudo: required
language: c
dist : trusty
compiler: clang
env:
    global:
        - LIBSODIUM_VER=1.0.12
        - MBEDTLS_VER=2.4.0
before_install:
    - wget https://github.com/jedisct1/libsodium/releases/download/$LIBSODIUM_VER/libsodium-$LIBSODIUM_VER.tar.gz
    - tar xvf libsodium-$LIBSODIUM_VER.tar.gz
    - pushd libsodium-$LIBSODIUM_VER
    - ./configure --prefix=/usr && make
    - sudo make install
    - popd
    - wget https://tls.mbed.org/download/mbedtls-$MBEDTLS_VER-gpl.tgz
    - tar xvf mbedtls-$MBEDTLS_VER-gpl.tgz
    - pushd mbedtls-$MBEDTLS_VER
    - make SHARED=1
    - sudo make install
    - popd
    # Load cached docker images
    - if [[ -d $HOME/docker ]]; then ls $HOME/docker/*.tar.gz | xargs -I {file} sh -c "zcat {file} | docker load"; fi
addons:
    apt:
        sources:
            - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
        packages:
            - libudns-dev
            - libev-dev
            - asciidoc
            - xmlto
script:
- ./autogen.sh && dpkg-buildpackage -b -us -uc
deploy:
  provider: releases
  api_key:
    secure: Lu6FkG0o02sS1ZbO6CZ9SV4fXs7f+TMebh6KtxxdKyN0cukdbed7C4L+hGzMygs9RQ3JqL6J4Ja2RbPMAOAhiQKbcFmi2e9G00Cza5o+jFX3tMqzn4s/zL0rh8lsmdHpEx2xNAnLkFyW6Ow5wzqtirG2QtT6oN83y/LfP1WgRt5wA3nWBREOT4KuGyiT5FhDYAhxptNyrKQFwqdtgIL6FOC3WxnwK4QEtgP5BOgyd91TLVstX02gO5D7zVeZweJZ+OkboLN4OfWd6j/Z4HUc9DUbWXxbzg7S45pSeTgFQzd/Mgn4i/u+hs3DO9GuPgjBXuGAr3VKqMcCvdcofm0lrDsfHxh5nkzhrHWPpiirjD3cyH3jIMMI6moeSRZJJbapJ4IO9XNcJ44QRkkarFNE/6a4ObSyj4aaJftXTqz3Kl20c243svzDaUv4Htg2oILKdL6ftOg/eSED35/LgTSsy5YdxH5arQf9MRU9mlJlLvciYSuRcDOQMtvEn1iuexz+G+QwxMPgNF9ZDM5u2wlgnNJz4HboBthM2A1nK7Qk2LAC4FUU9FPDYKOd0WOGJFC5VdG0QDokkSxOTAtSUhEFNSkaAmoWtGvZzkOOVjMaBr907eclRRNJytDqKwx1nd/Y2EXL4GyaB2QIchdugnptBvcvw/zDJUC7KPAvrT4QTwE=
  file: "../*.deb"
  skip_cleanup: true
  file_glob: true
  on:
    all_branches: true
    tags: true
