sudo: required
dist: trusty
language: c
compiler:
- gcc
addons:
  apt:
    packages:
    - autoconf
    - libtool
    - libssl-dev
    - gawk
    - debhelper
    - dh-systemd
    - init-system-helpers
    - pkg-config
    - asciidoc
    - xmlto
script:
- dpkg-buildpackage -b -us -uc -i
deploy:
  provider: releases
  api_key:
    secure: qwQu/39CxD38QotylRj1k9ujRieB/a9nMExDXKAwUgtGQ1iDxeKcWRKGf5dw2PYgVHMrfGj7/46QIYQw1rDeL85G6kM/TCGRYoaiZS2nRQ636GMSaL0/lAmoFCtvoV0CBiYcYgskxcM5Ezx1f9XqBusAviYMgnMJ+OTojKjUb6qvRMWRlc6vDpQ6Ym+zUnwTBskxPt7ypo9aNYVx+G1n9PCNfw03XumYBrt5Tab/bJDjI+AtFn/R5b9nS8oUdgeyHqTxE2qpfP8aOlRWs9g/D3mxeT2koy688PJaa92vUfd8+xn/RauG5omDOCckvM5zzI2tGcuJeAdspJUwvpJuLK4A1sjB8EZkfvLswspqmnZRFyWdlTTA1mF9ailkZYLvxv/XOCmmIoakuSaKwErvGvliPrZSfhnD+YKpMCbPVzsdNcjf8PCnHxNAvyWukMMhXCy1gXbiCRGtSvFBorPVM3uhLNRkFXNTWZl5LtaRf2oyHTqxgU9n7+GCv9vmjyujYpqriJ0xGP2+tpJQxgEQ5bzWbL6ZyaH+/PGuCfsKWpiW2RCkHppNPYZVf79qxAusFAqXIInYbqMN3REm0R8rYH6cl1SEnB9EJB+f65KojpoM5bIRp8P28NDi2SNenrLCqOXY3vcTKMYB/h8NNsQtVTl5+6IZUek7/rwqDfxpOyE=
  file: "../*.deb"
  skip_cleanup: true
  file_glob: true
  on:
    all_branches: true
    tags: true
